communications/urls.py
from django.urls import path
from .views import *

app_name = "communications"

urlpatterns = [
    path('', all_messages, name="all-messages"),
    path('<slug:friend>', messages_with_one_friend, name="messages-with-one-friend"),
]

core/urls.py
from django.urls import path
from .views import *

app_name = "core"

urlpatterns = [
    path('', home, name="home"),
]

socialnetwork/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('notifications.urls')),
    path('', include('core.urls')),
    path('', include('newsfeed.urls')),
    path('', include('friends.urls')),
    path('timeline/', include('userprofile.urls')),
    path('messages/', include('communications.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

communications/models.py
import uuid

from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Room(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    author = models.ForeignKey(User, related_name='author_room', on_delete=models.CASCADE)
    friend = models.ForeignKey(User, related_name='friend_room', on_delete=models.CASCADE)


class Message(models.Model):
    author = models.ForeignKey(User, related_name='author_messages', on_delete=models.CASCADE)
    friend = models.ForeignKey(User, related_name='friend_messages', on_delete=models.CASCADE)
    room = models.ForeignKey(Room, related_name='messages', on_delete=models.DO_NOTHING)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.message + " " + str(self.timestamp)

communications/views.py
import json

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils.safestring import mark_safe

from accounts.models import User
from friends.models import Friend


def all_messages(request):
    friends_one = Friend.objects.filter(friend=request.user, status='friend')
    friends_two = Friend.objects.filter(user=request.user, status='friend')
    friends = friends_one | friends_two
    return render(request, "communications/all-messages.html", {'friends': friends})


# Conversation with one friend
@login_required(login_url=reverse_lazy("accounts:login"))
def messages_with_one_friend(request, friend):
    if request.user.username == friend:
        return redirect(reverse_lazy('communications:all-messages'))
    try:
        if not User.objects.get(username=friend):
            return redirect(reverse_lazy('communications:all-messages'))
    except:
        return redirect(reverse_lazy('communications:all-messages'))
    friends_one = Friend.objects.filter(friend=request.user, status='friend')
    friends_two = Friend.objects.filter(user=request.user, status='friend')
    friends = friends_one | friends_two
    friend_user = User.objects.get(username=friend)
    return render(request, "communications/friend-messages.html", {
        'friends': friends,
        'friend_user': friend_user,
        'friend_name_json': mark_safe(json.dumps(friend)),
        'username': mark_safe(json.dumps(request.user.username)),
    })

templates/communications/all-messages.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <section>
        <div class="gap gray-bg">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="row" id="page-contents">
                            <div class="col-lg-3">
                                <aside class="sidebar static">
                                    <div class="widget stick-widget">
                                        <h4 class="widget-title">Shortcuts</h4>
                                        <ul class="naves">
                                            <li>
                                                <i class="ti-clipboard"></i>
                                                <a href="{% url 'core:home' %}" title="">News feed</a>
                                            </li>
                                            <li>
                                                <i class="ti-mouse-alt"></i>
                                                <a href="#" title="">Inbox</a>
                                            </li>
                                            <li>
                                                <i class="ti-user"></i>
                                                <a href="#" title="">friends</a>
                                            </li>
                                        </ul>
                                    </div><!-- Shortcuts -->
                                </aside>
                            </div><!-- sidebar -->
                            <div class="col-lg-6">
                                <div class="central-meta">
                                    <div class="messages">
                                        <h5 class="f-title"><i class="ti-bell"></i>All Messages </h5>
                                        <div class="message-box row">
                                            <ul class="peoples col-md-3">
                                                {% for friend in friends %}
                                                    <li>
                                                        <figure>
                                                            {% if friend.user.username == request.user.username %}
                                                                {% if friend.friend.gender == 'male' %}
                                                                    <img src="{% static 'images/male.jpg' %}" alt="male">
                                                                {% else %}
                                                                    <img src="{% static 'images/female.png' %}" alt="female">
                                                                {% endif %}
                                                            {% else %}
                                                                {% if friend.user.gender == 'male' %}
                                                                    <img src="{% static 'images/male.jpg' %}" alt="male">
                                                                {% else %}
                                                                    <img src="{% static 'images/female.png' %}" alt="female">
                                                                {% endif %}
                                                            {% endif %}
                                                            {#<span class="status f-online"></span>#}
                                                        </figure>
                                                        <div class="people-name">
                                                            {% if friend.user.username == request.user.username %}
                                                                <a href="{% url 'communications:messages-with-one-friend' friend.friend.username %}">{{ friend.friend.username }}</a>
                                                            {% else %}
                                                                <a href="{% url 'communications:messages-with-one-friend' friend.user.username %}">{{ friend.user.username }}</a>
                                                            {% endif %}
                                                        </div>
                                                    </li>
                                                {% endfor %}
                                            </ul>
                                            <div class="peoples-mesg-box col-md-9">
                                                <div class="text-center">
                                                    Select message to start conversation
                                                </div>
                                                {#                                                <div class="conversation-head">#}
                                                {#                                                    <figure><img src="images/resources/friend-avatar.jpg" alt=""></figure>#}
                                                {#                                                    <span>jason bourne <i>online</i></span>#}
                                                {#                                                </div>#}
                                                {#                                                <ul class="chatting-area">#}
                                                {#                                                    <li class="you">#}
                                                {#                                                        <figure><img src="images/resources/userlist-2.jpg" alt=""></figure>#}
                                                {#                                                        <p>what's liz short for? :)</p>#}
                                                {#                                                    </li>#}
                                                {#                                                    <li class="me">#}
                                                {#                                                        <figure><img src="images/resources/userlist-1.jpg" alt=""></figure>#}
                                                {#                                                        <p>Elizabeth lol</p>#}
                                                {#                                                    </li>#}
                                                {#                                                    <li class="me">#}
                                                {#                                                        <figure><img src="images/resources/userlist-1.jpg" alt=""></figure>#}
                                                {#                                                        <p>wanna know whats my second guess was?</p>#}
                                                {#                                                    </li>#}
                                                {#                                                    <li class="you">#}
                                                {#                                                        <figure><img src="images/resources/userlist-2.jpg" alt=""></figure>#}
                                                {#                                                        <p>yes</p>#}
                                                {#                                                    </li>#}
                                                {#                                                    <li class="me">#}
                                                {#                                                        <figure><img src="images/resources/userlist-1.jpg" alt=""></figure>#}
                                                {#                                                        <p>Disney's the lizard king</p>#}
                                                {#                                                    </li>#}
                                                {#                                                    <li class="me">#}
                                                {#                                                        <figure><img src="images/resources/userlist-1.jpg" alt=""></figure>#}
                                                {#                                                        <p>i know him 5 years ago</p>#}
                                                {#                                                    </li>#}
                                                {#                                                    <li class="you">#}
                                                {#                                                        <figure><img src="images/resources/userlist-2.jpg" alt=""></figure>#}
                                                {#                                                        <p>coooooooooool dude ;)</p>#}
                                                {#                                                    </li>#}
                                                {#                                                </ul>#}
                                                {#                                                <div class="message-text-container">#}
                                                {#                                                    <form method="post">#}
                                                {#                                                        <textarea></textarea>#}
                                                {#                                                        <button title="send"><i class="fa fa-paper-plane"></i></button>#}
                                                {#                                                    </form>#}
                                                {#                                                </div>#}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div><!-- centerl meta -->
                            <div class="col-lg-3">
                            </div><!-- sidebar -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/communications/friend-messages.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <section>
        <div class="gap gray-bg">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="row" id="page-contents">
                            <div class="col-lg-3">
                                <aside class="sidebar static">
                                    <div class="widget stick-widget">
                                        <h4 class="widget-title">Shortcuts</h4>
                                        <ul class="naves">
                                            <li>
                                                <i class="ti-clipboard"></i>
                                                <a href="{% url 'core:home' %}" title="">News feed</a>
                                            </li>
                                            <li>
                                                <i class="ti-mouse-alt"></i>
                                                <a href="inbox.html" title="">Inbox</a>
                                            </li>
                                            <li>
                                                <i class="ti-user"></i>
                                                <a href="timeline-friends.html" title="">friends</a>
                                            </li>
                                        </ul>
                                    </div><!-- Shortcuts -->
                                </aside>
                            </div><!-- sidebar -->
                            <div class="col-lg-6">
                                <div class="central-meta">
                                    <div class="messages" id="messages">
                                        <h5 class="f-title"><i class="ti-bell"></i>All Messages </h5>
                                        <div class="message-box row">
                                            <ul class="peoples col-md-3">
                                                {% for friend in friends %}
                                                    <li>
                                                        <figure>
                                                            {% if friend.user.username == request.user.username %}
                                                                {% if friend.friend.gender == 'male' %}
                                                                    <img src="{% static 'images/male.jpg' %}" alt="male">
                                                                {% else %}
                                                                    <img src="{% static 'images/female.png' %}" alt="female">
                                                                {% endif %}
                                                            {% else %}
                                                                {% if friend.user.gender == 'male' %}
                                                                    <img src="{% static 'images/male.jpg' %}" alt="male">
                                                                {% else %}
                                                                    <img src="{% static 'images/female.png' %}" alt="female">
                                                                {% endif %}
                                                            {% endif %}
                                                            {#<span class="status f-online"></span>#}
                                                        </figure>
                                                        <div class="people-name">
                                                            {% if friend.user.username == request.user.username %}
                                                                <a href="{% url 'communications:messages-with-one-friend' friend.friend.username %}">{{ friend.friend.username }}</a>
                                                            {% else %}
                                                                <a href="{% url 'communications:messages-with-one-friend' friend.user.username %}">{{ friend.user.username }}</a>
                                                            {% endif %}
                                                        </div>
                                                    </li>
                                                {% endfor %}
                                            </ul>
                                            <div class="peoples-mesg-box col-md-9">
                                                <div class="conversation-head">
                                                    <figure>
                                                        {% if friend_user.gender == 'male' %}
                                                            <img src="{% static 'images/male.jpg' %}" alt="male">
                                                        {% else %}
                                                            <img src="{% static 'images/female.png' %}" alt="female">
                                                        {% endif %}
                                                    </figure>
                                                    <span>Chat with {{ friend_name_json|slice:"1:-1" }}</span>
                                                </div>
                                                <ul class="chatting-area">
                                                </ul>
                                                <div class="message-text-container">
                                                    <form onsubmit="return false;">
                                                        <textarea id="chat-message-input"></textarea>
                                                        <em id="typing"></em>
                                                        <button title="send" id="chat-message-submit"><i class="fa fa-paper-plane"></i></button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

{% block scripts %}

    <script>
        $(document).ready(function () {
            let messages = $('.chatting-area');
            {#console.log(messages.prop("scrollHeight"));#}
            messages.animate({
                scrollTop: messages.offset().top + 50
            }, 'slow');
        });

        let friendName = {{ friend_name_json }};
        let username = {{ username }};

        let chatSocket = new ReconnectingWebSocket(
            'ws://' + window.location.host +
            '/ws/chat/' + friendName + '/');

        chatSocket.onopen = function (e) {
            fetchMessages();
        };

        chatSocket.onmessage = function (e) {
            let data = JSON.parse(e.data);
            if (data['command'] === 'messages') {
                for (let i = 0; i < data['messages'].length; i++) {
                    createMessage(data['messages'][i]);
                }
            } else if (data['command'] === 'new_message') {
                createMessage(data['message']);
            } else if (data['command'] === 'typing_start') {
                if (data["message"] !== friendName) {
                    document.getElementById("typing").innerHTML = data["message"] + " is typing";
                }
            } else if (data['command'] === 'typing_stop') {
                document.getElementById("typing").innerHTML = "";
            }
        };

        document.querySelector('#chat-message-input').addEventListener("keypress", function () {
            {#chatSocket.emit("typing", username);#}
            chatSocket.send(JSON.stringify({
                'command': 'typing_start',
                'from': friendName,
            }));
        });

        document.querySelector('#chat-message-input').addEventListener("keyup", function () {
            setTimeout(() => {
                chatSocket.send(JSON.stringify({
                    'command': 'typing_stop',
                }));
            }, 300);
        });

        {% comment %}chatSocket.ontyping = function (data) {
            console.log(data);
        };{% endcomment %}

        chatSocket.onclose = function (e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').onkeyup = function (e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function (e) {
            let messageInputDom = document.getElementById('chat-message-input');
            let message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'command': 'new_message',
                'message': message,
                'from': username,
                'friend': friendName
            }));

            messageInputDom.value = '';

            let messages = $('#messages');
            messages.animate({
                scrollTop: messages.offset().top + 50
            }, 1000);
        };

        function fetchMessages() {
            chatSocket.send(JSON.stringify({'command': 'fetch_messages', 'author': username, 'friend': friendName}));
        }

        function createMessage(data) {
            let author = data['author'];
            let user_class;
            let gender_image;

            if (author === username) {
                user_class = "me";
                if (data['author_gender'] === 'male') gender_image = "{% static 'images/male.jpg' %}";
                else gender_image = "{% static 'images/female.png' %}"
            } else {
                user_class = "you";
                if (data['author_gender'] === 'male') gender_image = "{% static 'images/male.jpg' %}";
                else gender_image = "{% static 'images/female.png' %}"
            }

            let message = `<li class="${user_class}">
                                <figure>
                                    <img src="${gender_image}" alt="">
                                </figure>
                                <p>${data.content}</p>
                            </li>`;

            $('.chatting-area').append(message);
        }
    </script>

{% endblock %}